export const ACTION_TYPE = {
    GET_TODOS: "GET_TODOS",
    DELETE_TODOS: "DELETE_TODOS",
    ADD_TODOS: "ADD_TODOS",
    UPDATE_TODOS: "UPDATE_TODOS",
    GET_SORT: "GET_SORT",
    UPDATE_SORT: "UPDATE_SORT",
    GET_SEARCH: "GET_SEARCH",
    UPDATE_SEARCH: "UPDATE_SEARCH",
};
